# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Configuration
  
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Introduction
    output: single
    url: /configuration/introduction.html
    folderitems:
    -
    
  - title: Company
    output: single
    url: /configuration/company.html
    folderitems:
    -
    
  - title: Campus
    output: single
    url: /configuration/campus.html
    folderitems:
    -
    
  - title: Material Department
    output: single
    url: /configuration/material-department.html
    folderitems:
    -
    
  - title: MasterHR Details
    output: single
    url: /configuration/master-hr-details.html
    folderitems:
    -

  - title: Security Configuration
    output: single
    url: /configuration/security-configuration.html
    folderitems:
    -
